api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    url(r'^$', views.EntryList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9a-zA-Z]+)/$', views.EntryDetail.as_view(), name='detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

control/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # Management
    url(r'^values/?$', views.values, name='values'),
    url(r'^manual/?$', views.manual, name='manual'),
    url(r'^bulk/?$', views.bulk, name='bulk'),
    url(r'^apikeys/?$', views.apikeys, name='apikeys'),

    # Operations
    url(r'^mapreduce/?', views.mapreduce, name='mapreduce'),
    url(r'^conditionals/?', views.conditionals, name='conditionals'),

    # Settings
    url(r'^restrictions/?$', views.restrictions, name='restrictions'),

    # Form submits
    url(r'^generate_apikey/$', views.generate_apikey, name='generate_apikey'),
    url(r'^delete_apikey/$', views.delete_apikey, name='delete_apikey'),
]

keyvalue/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index-index"),

    url(r'^features/$', views.features, name="index-features"),
    url(r'^about/$', views.about, name="index-about"),
    url(r'^documentation/$', views.documentation, name='documentation'),

    url(r'^control/', include('control.urls', namespace="control")),
    url(r'^api/', include('api.urls', namespace='api')),

    url(r'^login/?$', views.login, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^register/$', views.register, name='register'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

control/models.py
from django.db import models

control/views.py
from django.shortcuts import render
from api.models import Entry, Token
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

from keyvalue.utility import create_token

@login_required
def index(request):
    return render(request, 'control/control.html')


''' Management '''
@login_required
def values(request):
    entries = Entry.objects.all()
    return render(request, 'control/management/values.html', {'active': 'values', 'entries': entries})

@login_required
def manual(request):
    return render(request, 'control/management/manual.html', {'active': 'manual'})

@login_required
def bulk(request):
    return render(request, 'control/management/bulk.html', {'active': 'bulk'})

''' Operations '''
@login_required
def mapreduce(request):
    return render(request, 'control/operations/mapreduce.html', {'active': 'mapreduce'})

@login_required
def conditionals(request):
    return render(request, 'control/operations/conditionals.html', {'active': 'conditionals'})


@login_required
def apikeys(request):
    key_root = request.user.apikey_set.get(is_key_root=True)
    key_generate = request.user.apikey_set.get(is_key_generate=True)
    keys = request.user.apikey_set.filter(is_key_root=None, is_key_generate=None).order_by('created_time')
    return render(request, 'control/management/apikeys.html', {'active': 'apikeys',
                                                               'keys': keys,
                                                               'key_root': key_root,
                                                               'key_generate': key_generate
                                                               })


''' Settings '''
@login_required
def restrictions(request):
    return render(request, 'control/settings/restrictions.html', {'active': 'restrictions'})


''' Form submits '''
@login_required
def generate_apikey(request):
    if request.method == 'POST':
        create_token(request.user, request)

    return redirect('control:apikeys')

@login_required
def delete_apikey(request):
    if request.method == 'POST':
        try:
            key = request.user.apikey_set.get(key=request.POST['key'])
            key.delete()
        except Token.DoesNotExist:
            pass

    return redirect('control:apikeys')

control/templates/control/control.html
{% extends 'base.html' %}
{% block content %}

    <div class="row">
        <div class="col-md-2">

{#            <div class="affix-fixed">#}

                <div class="btn-group-vertical navbar">
                    <button class="btn btn-primary disabled nocursor" style="cursor:default;"><b>Management</b></button>
                    <a href="{% url 'control:values' %}" class="btn btn-default {% if  active == 'values' %}active{% endif %}">My values</a>
                    <a href="{% url 'control:manual' %}" class="btn btn-default {% if  active == 'manual' %}active{% endif %}">Manual entry</a>
                    <a href="{% url 'control:bulk' %}" class="btn btn-default {% if  active == 'bulk' %}active{% endif %}">Bulk access</a>
                    <a href="{% url 'control:apikeys' %}" class="btn btn-default {% if  active == 'apikeys' %}active{% endif %}">API keys</a>
                </div>

                <div class="btn-group-vertical navbar">
                    <button class="btn btn-primary disabled nocursor" style="cursor:default;"><b>Operations</b></button>
                    <a href="{% url 'control:mapreduce' %}" class="btn btn-default {% if  active == 'mapreduce' %}active{% endif %}">MapReduce</a>
                    <a href="{% url 'control:conditionals' %}" class="btn btn-default {% if  active == 'conditionals' %}active{% endif %}">Conditionals</a>
                </div>

                <div class="btn-group-vertical navbar">
                    <button class="btn btn-primary disabled nocursor" style="cursor:default;"><b>Settings</b></button>
                    <a href="{% url 'control:restrictions' %}" class="btn btn-default {% if  active == 'restrictions' %}active{% endif %}">Restrictions</a>
                </div>

{#            </div>#}
        </div>
        <div class="col-md-8">
            {% block control %}
                <div class="row row-main">
                    <h2> Control center </h2>
                </div>
            {% endblock %}
        </div>
    </div>
{% endblock %}