api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    url(r'^$', views.EntryList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9a-zA-Z]+)/$', views.EntryDetail.as_view(), name='detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

control/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # Management
    url(r'^values/?$', views.values, name='values'),
    url(r'^manual/?$', views.manual, name='manual'),
    url(r'^bulk/?$', views.bulk, name='bulk'),
    url(r'^apikeys/?$', views.apikeys, name='apikeys'),

    # Operations
    url(r'^mapreduce/?', views.mapreduce, name='mapreduce'),
    url(r'^conditionals/?', views.conditionals, name='conditionals'),

    # Settings
    url(r'^restrictions/?$', views.restrictions, name='restrictions'),

    # Form submits
    url(r'^generate_apikey/$', views.generate_apikey, name='generate_apikey'),
    url(r'^delete_apikey/$', views.delete_apikey, name='delete_apikey'),
]

keyvalue/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index-index"),

    url(r'^features/$', views.features, name="index-features"),
    url(r'^about/$', views.about, name="index-about"),
    url(r'^documentation/$', views.documentation, name='documentation'),

    url(r'^control/', include('control.urls', namespace="control")),
    url(r'^api/', include('api.urls', namespace='api')),

    url(r'^login/?$', views.login, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^register/$', views.register, name='register'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

templates/base.html
{% load staticfiles %}
{% with title="World" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link href="{% static "navbar.css" %}" rel="stylesheet">

</head>

<body>

<div class="container">

    <nav class="navbar navbar-default">
        <div class="container-fluid">


            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index-index' %}">{{ title }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'documentation' %}">API documentation</a></li>
                    <li><a href="{% url 'index-features' %}">Features</a></li>
                    <li><a href="{% url 'index-about' %}">About</a></li>
                </ul>


                <ul class="nav navbar-nav navbar-right">

                    {% if user.is_authenticated %}
                        <li><p class="navbar-text hidden-xs hidden-sm">Welcome <b>{{ user.username }}</b></p></li>
                        <li><a href="{% url 'control:index' %}">Control center </a></li>
                        <li>
                            <form method="post" action="{% url 'logout' %}" class="navbar-form" style="max-width:100%;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Sign out</button>
                            </form>
                        </li>

                    {% else %}

                        <form method="post" action="{% url 'login' %}" class="navbar-form navbar-nav" style="max-width:100%;">
                            {% csrf_token %}

                            <input type="text" class="form-control" placeholder="Username or email" name="id" required/>
                            <input type="password" class="form-control" placeholder="Password" name="password" required/>

                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </form>

                    {% endif %}

                </ul>

            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer text-center">
        <p>&copy; Martijn Bakker 2015</p>
    </footer>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

{% endwith %}